//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cracker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About... 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:yyyy-MM-dd} update. Total {1} addresses load completed! 的本地化字符串。
        /// </summary>
        public static string AddressLoadedFormat {
            get {
                return ResourceManager.GetString("AddressLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:yyyy-MM-dd} update. Total {1} addresses loading... 的本地化字符串。
        /// </summary>
        public static string AddressLoadingFormat {
            get {
                return ResourceManager.GetString("AddressLoadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We will start to crack after addresses loaded! 的本地化字符串。
        /// </summary>
        public static string CrackAfterAddressLoaded {
            get {
                return ResourceManager.GetString("CrackAfterAddressLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crack Probability Per Day:  的本地化字符串。
        /// </summary>
        public static string CrackProbabilityPerDay {
            get {
                return ResourceManager.GetString("CrackProbabilityPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crack Speed:  的本地化字符串。
        /// </summary>
        public static string CrackSpeed {
            get {
                return ResourceManager.GetString("CrackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /s 的本地化字符串。
        /// </summary>
        public static string CrackSpeedUnit {
            get {
                return ResourceManager.GetString("CrackSpeedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crack successful! Address: {0} Private Key: {1} !!! 的本地化字符串。
        /// </summary>
        public static string CrackSuccessfulFormat {
            get {
                return ResourceManager.GetString("CrackSuccessfulFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination Address:  的本地化字符串。
        /// </summary>
        public static string DestinationAddress {
            get {
                return ResourceManager.GetString("DestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address load completed! 的本地化字符串。
        /// </summary>
        public static string FinishLoadAddress {
            get {
                return ResourceManager.GetString("FinishLoadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Window 的本地化字符串。
        /// </summary>
        public static string HideWindow {
            get {
                return ResourceManager.GetString("HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No address! Please update address first! 的本地化字符串。
        /// </summary>
        public static string NoAddressTip {
            get {
                return ResourceManager.GetString("NoAddressTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Window 的本地化字符串。
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Crack 的本地化字符串。
        /// </summary>
        public static string StartCrack {
            get {
                return ResourceManager.GetString("StartCrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start to load address! 的本地化字符串。
        /// </summary>
        public static string StartToLoadAddress {
            get {
                return ResourceManager.GetString("StartToLoadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Crack 的本地化字符串。
        /// </summary>
        public static string StopCrack {
            get {
                return ResourceManager.GetString("StopCrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitcoin cracker is here now! 的本地化字符串。
        /// </summary>
        public static string SystemTrayTip {
            get {
                return ResourceManager.GetString("SystemTrayTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thread Count: 的本地化字符串。
        /// </summary>
        public static string ThreadCount {
            get {
                return ResourceManager.GetString("ThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the thread count! 的本地化字符串。
        /// </summary>
        public static string ThreadCountTip {
            get {
                return ResourceManager.GetString("ThreadCountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitcoin Cracker (www.xiaonh.com) 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Address 的本地化字符串。
        /// </summary>
        public static string UpdateAddress {
            get {
                return ResourceManager.GetString("UpdateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Software 的本地化字符串。
        /// </summary>
        public static string UpdateSoftware {
            get {
                return ResourceManager.GetString("UpdateSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon xiaonh {
            get {
                object obj = ResourceManager.GetObject("xiaonh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
